AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  build-ai-system-backend-lambda-python

  Sample SAM Template for build-ai-system-backend-lambda-python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  BuildAISystemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build-ai-system/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64

    Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: POST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BuildAISystemApi:
    Description: API Gateway endpoint URL for Prod stage for BuildAISystem function
    Value: !Sub "https://${BuildAISystemApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}/"
  BuildAISystemFunction:
    Description: BuildAISystem Lambda Function ARN
    Value: !GetAtt BuildAISystemFunction.Arn
  BuildAISystemFunctionIamRole:
    Description: Implicit IAM Role created for BuildAISystem function
    Value: !GetAtt BuildAISystemFunctionRole.Arn
